plugin:
    has_options: false

    resources:
      - class: Icap\LessonBundle\Entity\Lesson
        name: icap_lesson
        is_browsable: true
        is_exportable: false
        #icon: res_text.png
        #actions:
          #- name: open
            #is_action_in_new_page: true